### ISSUE TITLE
ModuleNotFoundError occurred during training

### ISSUE THREAD

**Issue by LJP-Perfect** [lambert-x/video-semisup#3]
The following error occurs when running the dist_train_semi.sh script.

Traceback (most recent call last):
  File "tools/train_semi.py", line 15, in <module>
    from mmaction.apis import train_model
  File "/home/ljp/video-semisup/mmaction/apis/__init__.py", line 1, in <module>
    from .inference import inference_recognizer, init_recognizer
  File "/home/ljp/video-semisup/mmaction/apis/inference.py", line 13, in <module>
    from mmaction.models import build_recognizer
  File "/home/ljp/video-semisup/mmaction/models/__init__.py", line 21, in <module>
    from .recognizers import (AudioRecognizer, BaseRecognizer, Recognizer2D,
  File "/home/ljp/video-semisup/mmaction/models/recognizers/__init__.py", line 14, in <module>
    from .recognizer3d_semi_appsup_tempsup_simclr_crossclip import Semi_AppSup_TempSup_SimCLR_Crossclip_Recognizer3D
**ModuleNotFoundError: No module named 'mmaction.models.recognizers.recognizer3d_semi_appsup_tempsup_simclr_crossclip'**

**Comment by lambert-x** [comment]
Please pull again and check if the bug is fixed. I tried to clean the code but still need several rounds. Please let me know if you have any other issues.
